import test from 'node:test';
import assert from 'node:assert/strict';
import {Calculator} from '../src/calculator.js';
const keys={A:'SQRT',B:'EXP',C:'POW10',D:'POWER',E:'RECIP'};
function run(c,seq){for(const key of seq.split(' ')){if(/^\d{2,}$/.test(key))for(const d of key)c.press(d);else c.press(key);}return c;}
function setup(matrices){const c=new Calculator();for(const [name,rows] of Object.entries(matrices)){run(c,`${rows.length} ENTER ${rows[0].length} f SIN ${keys[name]} f CHS 1`);if(!c.user)run(c,'f RCL');for(const v of rows.flat()){run(c,'CLX');run(c,String(Math.abs(v)));if(v<0)c.press('CHS');run(c,`STO ${keys[name]}`);}if(c.user)run(c,'f RCL');}assert.equal(c.error,false);return c;}
function recall(c,name){run(c,`RCL CHS ${keys[name]}`);}
function result(c,name){run(c,`f EEX ${keys[name]}`);}
const data=(c,n)=>c.matrices[n].data;
test('critic matrix handbook USER sequential entry and wrap',()=>{const c=setup({A:[[1,2,3],[4,5,6]]});assert.deepEqual(data(c,'A'),['1','2','3','4','5','6']);assert.deepEqual(c.registers.slice(0,2),['1','1']);run(c,'f RCL');const vals=[];for(let i=0;i<6;i++){run(c,'RCL SQRT');vals.push(c.stack[0]);}assert.deepEqual(vals,['1','2','3','4','5','6']);assert.deepEqual(c.registers.slice(0,2),['1','1']);});
test('critic matrix stack-index store and recall preserve documented stack',()=>{const c=setup({A:[[1,2],[3,4]]});run(c,'9 ENTER 2 ENTER 1 STO g SQRT');assert.equal(c.stack[0],'9');assert.equal(data(c,'A')[2],'9');run(c,'2 ENTER 1 RCL g SQRT');assert.equal(c.stack[0],'9');assert.deepEqual(c.registers.slice(0,2),['1','1']);});
test('critic matrix resizing retains linear order',()=>{const c=setup({A:[[1,2,3],[4,5,6]]});run(c,'3 ENTER 2 f SIN SQRT');assert.deepEqual(data(c,'A'),['1','2','3','4','5','6']);run(c,'2 ENTER 2 f SIN SQRT');assert.deepEqual(data(c,'A'),['1','2','3','4']);});
test('critic descriptor storage and persistence retain live matrix dimensions',()=>{const c=setup({A:[[1,2],[3,4]]});recall(c,'A');run(c,'STO 5');const d=new Calculator(JSON.parse(JSON.stringify(c.save())));run(d,'RCL 5');assert.equal(d.stack[0],'@A');assert.deepEqual(data(d,'A'),['1','2','3','4']);assert.equal(d.display().mantissa,'A 2 2');});
test('critic matrix scalar divided by matrix is scaled inverse',()=>{const c=setup({A:[[4,7],[2,6]]});result(c,'B');run(c,'2 ENTER');recall(c,'A');c.press('/');assert.equal(c.error,false);assert.deepEqual(data(c,'B'),['1.2','-1.4','-0.4','0.8']);});
test('critic matrix multiplication prohibits either input as result and rolls back',()=>{const c=setup({A:[[1,2],[3,4]],B:[[2,0],[0,2]]});recall(c,'A');recall(c,'B');result(c,'A');const before=structuredClone(c.matrices);c.press('*');assert.equal(c.errorCode,11);assert.deepEqual(c.matrices,before);});
test('critic MATRIX5 handbook ATB oracle',()=>{const c=setup({A:[[1,2,3],[4,5,9]],B:[[1,3,5],[7,9,17]]});recall(c,'A');recall(c,'B');result(c,'C');run(c,'f CHS 5');assert.equal(c.error,false);assert.deepEqual(data(c,'C'),['29','39','73','37','51','95','66','90','168']);assert.deepEqual(data(c,'A'),['1','2','3','4','5','9']);});
test('critic MATRIX6 residual oracle',()=>{const c=setup({A:[[1,2],[3,4]],B:[[2],[3]],C:[[10],[20]]});recall(c,'A');recall(c,'B');result(c,'C');run(c,'f CHS 6');assert.equal(c.error,false);assert.deepEqual(data(c,'C'),['2','2']);});
test('critic MATRIX2 and3 handbook block transform in place',()=>{const c=setup({A:[[1,-6],[-4,5]]});recall(c,'A');run(c,'f CHS 2');assert.deepEqual(data(c,'A'),['1','-6','4','-5','-4','5','1','-6']);run(c,'f CHS 3');assert.deepEqual(data(c,'A'),['1','-6','-4','5']);});
test('critic permutation and combination matrix packing handbook oracle',()=>{const c=setup({A:[[4,3,7,-2],[1,5,3,8]]});recall(c,'A');run(c,'f +');assert.deepEqual(data(c,'A'),['4','7','1','3','3','-2','5','8']);assert.equal(c.matrices.A.rows,4);run(c,'g +');assert.deepEqual(data(c,'A'),['4','3','7','-2','1','5','3','8']);assert.equal(c.matrices.A.rows,2);});
test('critic MATRIX4 transpose preserves original result selection',()=>{const c=setup({A:[[1,2,3],[4,5,6]],B:[[9]]});result(c,'B');recall(c,'A');run(c,'f CHS 4');assert.deepEqual(data(c,'A'),['1','4','2','5','3','6']);assert.deepEqual(data(c,'B'),['9']);});
test('critic MATRIX7 and8 norm oracle and LASTX',()=>{const c=setup({A:[[1,2,3],[4,5,9]]});recall(c,'A');run(c,'f CHS 7');assert.equal(c.stack[0],'18');assert.equal(c.lastX,'@A');recall(c,'A');run(c,'f CHS 8');assert.equal(c.stack[0],'11.66190379');});
test('critic MATRIX9 puts LU in result and reuses original determinant',()=>{const c=setup({A:[[4,7],[2,6]]});result(c,'B');recall(c,'A');run(c,'f CHS 9');assert.equal(c.stack[0],'10');assert.deepEqual(data(c,'A'),['4','7','2','6']);assert.ok(c.matrices.B.lu);recall(c,'B');result(c,'C');run(c,'f CHS 9');assert.equal(c.stack[0],'10');});
test('critic divide preserves reusable coefficient LU and allows resultY',()=>{const c=setup({A:[[0,1],[1,2]],B:[[1],[4]]});result(c,'B');recall(c,'B');recall(c,'A');c.press('/');assert.equal(c.error,false);assert.deepEqual(data(c,'B'),['2','1']);assert.ok(c.matrices.A.lu);recall(c,'A');result(c,'C');c.press('RECIP');assert.deepEqual(data(c,'C'),['-2','1','1','0']);});
test('critic memory accounts for shared matrix storage and complex stack',()=>{const c=new Calculator();run(c,'6 ENTER 7 f SIN SQRT');assert.equal(c.error,false);run(c,'g 4 8');assert.equal(c.errorCode,10);assert.equal(c.flags[8],false);c.press('BACK');run(c,'f CHS 0');assert.equal(c.advanced.free(),46);run(c,'g 4 8');assert.equal(c.flags[8],true);assert.equal(c.advanced.free(),41);});
test('critic 64 element maximum requires DIM(i)1 and rejects extra',()=>{const c=new Calculator();run(c,'1 f SIN COS 8 ENTER 8 f SIN SQRT');assert.equal(c.error,false);assert.equal(c.advanced.free(),0);run(c,'1 ENTER 1 f SIN EXP');assert.equal(c.errorCode,10);assert.equal(c.matrices.B.data.length,0);});
test('critic restrictions distinguish descriptor misuse and bad element',()=>{const c=setup({A:[[1]]});recall(c,'A');c.press('SIN');assert.equal(c.errorCode,1);c.press('BACK');run(c,'2 ENTER 1 RCL g SQRT');assert.equal(c.errorCode,3);});
