// Physical keys resolve once; an unsupported shift never falls through to its base key.
export const shiftedKeys = {
 f: {CHS:'MATRIX',SIN:'DIM',COS:'IM_VIEW',TAN:'MAKE_COMPLEX',EEX:'RESULT',4:'EXCHANGE',5:'DSE',6:'ISG',GSB:'CLEAR_STATS',SWAP:'CLEAR_REG',BACK:'PREFIX',ENTER:'RANDOM','-':'RE_IM',RCL:'USER','.':'ESTIMATE',SUM:'REGRESSION','/':'SOLVE','*':'INTEGRATE',0:'FACTORIAL',1:'RECT',2:'HMS',3:'TO_RAD','+':'PERMUTE',STO:'FRAC',7:'FIX',8:'SCI',9:'ENG',GTO:'HYP'},
 g: {4:'SF',5:'CF',6:'FLAG','-':'TEST',RCL:'MEM',0:'MEAN','.':'STD',SUM:'SUM_MINUS','/':'X_LE_Y','*':'X_EQ_0',1:'POLAR',2:'HOURS',3:'TO_DEG','+':'COMBINE',7:'DEG',8:'RAD',9:'GRAD',SIN:'ASIN',COS:'ACOS',TAN:'ATAN',GTO:'AHYP',BACK:'CLX',ENTER:'LASTX',SQRT:'SQUARE',EXP:'LN',POW10:'LOG',POWER:'PERCENT',RECIP:'DELTA_PERCENT',CHS:'ABS',EEX:'PI',STO:'INT',SWAP:'RND',ROLL:'ROLLUP'},
};
